# Generated by Django 2.2.3 on 2019-11-13 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aricle',
            new_name='Article',
        ),
    ]
